### ISSUE TITLE
KeyError: 'token'

### ISSUE THREAD

**Issue by szabosa** [koltayk/myT#1]
[user@machine: ~ ]$ python3 mytgettrips.py 
Traceback (most recent call last):
  File "~/myT/mytgettrips.py", line 143, in <module>
    token= resp_json['token']
KeyError: 'token'

szerintem ez a link már nem él: https://ssoms.toyota-europe.com/authenticate

**Comment by koltayk** [comment]
Nálam működik.
username, pwd rendben van?

**Comment by szabosa** [comment]
Nálam volt a baj, pw hashelés nem volt jó.
