### ISSUE TITLE
Traceback in <module> write_json_gpx(recent_trip, trip_json, line 87, in write_json_gpx with open(f"{json_dir}{desc}.json", "w", encoding='utf-8')

### ISSUE THREAD

**Issue by szabosa** [koltayk/myT#2]
Szlovák településnél belefutottam egy ilyenbe:

`Traceback (most recent call last):
  File "/mytoyota/./mytgettrips_yearly.py", line 179, in <module>
    write_json_gpx(recent_trip, trip_json)
  File "/mytoyota/./mytgettrips_yearly.py", line 87, in write_json_gpx
    with open(f"{json_dir}{desc}.json", "w", encoding='utf-8') as outfile:
FileNotFoundError: [Errno 2] No such file or directory: '/mytoyota/exported/yearly/json/2023-09-20T15:27:18Z Námestie László Kovácsa 335/2, 932 01 Veľký Meder, Trnava, Slovakia - 2023-09-20T15:55:56Z 1396, 929 01 Kútniky, Trnava, Slovakia.json'`

**Comment by koltayk** [comment]
A 2023-09-20T15:27:18Z Námestie László Kovácsa 335/2, 932 01 Veľký Meder, Trnava, Slovakia - 2023-09-20T15:55:56Z 1396, 929 01 Kútniky, Trnava, Slovakia.json 
fájl nevében a "/" jel okozza a problémát.
Javítva.

**Comment by szabosa** [comment]
Köszi, tesztelve, működik! :)
